const initialTasks=[{id:1,title:'晨读《昆虫记》',meta:'语文 · 20分钟',points:10,done:true},{id:2,title:'数学口算练习',meta:'数学 · 30道',points:15,done:true},{id:3,title:'英语单词打卡',meta:'英语 · Unit 3',points:10,done:true},{id:4,title:'跳绳运动',meta:'运动 · 20分钟',points:15,done:false},{id:5,title:'整理自己的书桌',meta:'生活 · 10分钟',points:10,done:false}];
const rewards=[{icon:'🎨',name:'自由画画 30 分钟',cost:50,desc:'尽情画出你的想象'},{icon:'🍦',name:'冰淇淋一支',cost:80,desc:'夏天的小小甜蜜'},{icon:'🎮',name:'游戏时间 30 分钟',cost:120,desc:'完成计划才能兑换'},{icon:'📚',name:'想看的书一本',cost:200,desc:'去发现新的世界'}];
let state=JSON.parse(localStorage.getItem('summerCareState')||'null')||{tasks:initialTasks,points:280};
const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
function save(){localStorage.setItem('summerCareState',JSON.stringify(state))}
function renderTasks(){const done=state.tasks.filter(t=>t.done).length;$('#taskList').innerHTML=state.tasks.map(t=>`<div class="task-item ${t.done?'done':''}"><button class="check-button" data-task="${t.id}" aria-label="${t.done?'取消':'完成'}任务">✓</button><div class="task-main"><strong>${t.title}</strong><small>${t.meta}</small></div><span class="task-points">+${t.points}</span></div>`).join('');$('#progressText').textContent=`${done}/${state.tasks.length}`;$('#progressBar').style.width=`${done/state.tasks.length*100}%`;$('#progressHint').textContent=done===state.tasks.length?'太棒了，今日计划全部完成！':`还剩 ${state.tasks.length-done} 项，加油！`;$('#heroCaption').textContent=done===state.tasks.length?'今日计划已全部点亮，去领取你的奖励吧！':'完成今天的计划，就能点亮一颗星星';$$('[data-task]').forEach(b=>b.onclick=()=>toggleTask(Number(b.dataset.task)))}
function toggleTask(id){const task=state.tasks.find(t=>t.id===id);if(!task)return;task.done=!task.done;state.points+=task.done?task.points:-task.points;save();render();toast(task.done?`完成「${task.title}」 +${task.points} 积分`:'已取消这项打卡')}
function renderRewards(){const chips=rewards.slice(0,3).map(r=>`<div class="reward-chip"><div class="reward-art">${r.icon}</div><strong>${r.name}</strong><small>${r.cost} 积分</small></div>`).join('');$('#rewardStrip').innerHTML=chips;$('#rewardGrid').innerHTML=rewards.map(r=>`<div class="reward-card"><div class="reward-art">${r.icon}</div><strong>${r.name}</strong><p>${r.desc}</p><button data-reward="${r.cost}" ${state.points<r.cost?'disabled':''}>${state.points<r.cost?'积分不够':`兑换 · ${r.cost} 分`}</button></div>`).join('');$('#balanceText').textContent=state.points;$('#pointsText').textContent=state.points;$$('[data-reward]').forEach(b=>b.onclick=()=>redeem(Number(b.dataset.reward)))}
function redeem(cost){if(state.points<cost)return;state.points-=cost;save();renderRewards();toast('兑换成功，记得找家长领取哦！')}
function renderChart(){const values=[3,2,4,3,1,2,1];$('#barChart').innerHTML=values.map((v,i)=>`<div class="bar ${i===2?'today':''}" style="height:${v/4*100}%" data-value="${v}"></div>`).join('')}
function render(){renderTasks();renderRewards();renderChart()}
function showScreen(id){$$('.screen').forEach(s=>s.classList.toggle('hidden',s.id!==id));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.screen===id));window.scrollTo({top:0,behavior:'smooth'})}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
$$('.nav-item[data-screen]').forEach(n=>n.onclick=()=>showScreen(n.dataset.screen));$('#viewAllRewardsBtn').onclick=()=>showScreen('rewardsScreen');$('#editPlanBtn').onclick=()=>toast('计划编辑功能即将开放，可以先完成今天的任务哦');$('#notifyBtn').onclick=()=>toast('今天 18:00 有一条待完成计划');$('#profileBtn').onclick=()=>toast('小满 · 暑假第 12 天');
render();
